### ISSUE TITLE
HFI Calculator: Weekly View / Prep Cycle

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1002]
Nov 17: 
- 

May 11: 
Table View includes:
- Selec/deselect a Wx in a planning area for Mean calculation
- both tables are populated with automation and NO manual inputs
- need to determine true sources for the data used to fill the tables
- Video of table being filled manually: [Link to Video]
(https://bcgov.sharepoint.com/:v:/r/teams/01324/Shared%20Documents/General/UX/HFI-Prep%20Tool/HFI%20Cal%20Process%20Walkthrough%20Videos/peter%20oh%20sad%20ski%20-%20Meeting%20in%20_Preparedness_-20210319_085330-Meeting%20Recording.mp4?csf=1&web=1)

- Link to where the report is generated: http://bcfireweatherp1.nrs.gov.bc.ca/Scripts/Public/Common/Report.asp?Report=Daily

- Weekly View Columns:
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/d00c778e-0bf8-4acb-a465-64e35dac7fb4)

- ability to add/remove a WX station from the calculated prep for the planning area (MVP)
- expand and collapse of Fire Centers
-expand and collapse planning areas

# Dependencies

## Epic

- [ ] bcgov/wps/issues/1022
- [ ] bcgov/wps/issues/1023
- [ ] bcgov/wps/issues/1552
- [ ] bcgov/wps/issues/1557
- [ ] bcgov/wps/issues/1559
