### ISSUE TITLE
FireBAT: table front-end and usability improvements

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1153]
Buttons, column grouping, alignment and spacing, table behaviour

**Additional Context**
- Design work pulled out of #1141

**Acceptance Criteria**
Broken into many tickets:
- [ ] #1245 freeze first columns on horizontal scroll **# 1**
- [ ] #1190 table reloads on date change in picker 
- [ ] #1239 export to CSV button and copy/paste behaviour (bug + new feature)
- [ ] #1242 button hierarchy for table actions (refresh, delete, export)
- [ ] #1096 HFI threshold color coding
- [ ] #1243 table dividers for scannability 
- [ ] #1244 table header alignment for scannability 
- [ ]  #1246 table empty state: copy/instructions 
- [x] #1164 freeze table header and modify CSS sizing (padding, height, font size)
- [x] #1095 column sorting
- [x] #1211 smart calculate - only reload row(s) that changed 
- [x] Change width of date input field so label text doesn't wrap
- [x] When wind speed is adjusted, a bold/coloured style is applied to the Adjusted status label and the wind speed value that changed (usability heuristics: _visibility of system status_, _recognition rather than recall_) - it was working, we lost it in table merge (wind speed went from text to input field)
- [x] ~(Low priority) Collapse weather and fire indices groups (like collapsing pipelines in zenhub)~ testers have indicated this is not helpful. Investigate freezing first columns (checkbox + station name)
