### ISSUE TITLE
FireBAT Table: Display a summarized table of key data points to be included in the FBA

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1536]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

# Dependencies

## Epic

- [ ] bcgov/wps/issues/1537
- [ ] bcgov/wps/issues/1538
