### ISSUE TITLE
HFI Calculator - KFC Proto: Interface iterations (from usability testing)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1541]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

# Dependencies

## Epic

- [ ] bcgov/wps/issues/1555
- [ ] bcgov/wps/issues/1558
- [ ] bcgov/wps/issues/1570
- [ ] bcgov/wps/issues/1571
