### ISSUE TITLE
HFI Calculator: Unofficial Fuel Types in use

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1543]
**As a** *FBAN/FBS* **I want** *any new ops technology developed to take into account my current methods of calculating fire behaviour indices/predicted behaviour* **So That** *I can continue to produce the most accurate fire behaviour work possible*

**Additional Context**
- Several 'unofficial' fuel types are emerging — they have emerged because the national standards for fuel types may not take into account specific BC context when it comes to topography, weather, and fuels 
- a user asks "what's the bigger liability, using an unofficial fuel type, or working with values we know are inaccurate" (they understand the liability, they're just making a point) 
- BL - Blended, Coastal
- C7b - re: grass curing, Kamloops, Southeast 
- C3m - newly discovered, investigating 

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

# Dependencies

## Epic

- [ ] bcgov/wps/issues/1108
