### ISSUE TITLE
HFI Calc Interface Guidance [Figma]

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1657]
**Describe the task**
Interfaces and acceptance criteria/screenshots to support recent HFI decisions

**Acceptance Criteria**
- [x] storm on #1634 all users see changes interactions
- [x] interaction and UI on #1585 forecasting timestamp 
- [x] create responsive epic #1662

**Additional context**
- Add any other context about the task here.
- Or here
