### ISSUE TITLE
Responsive design & dev strategy

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1662]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- Resources
  - [A Book Apart # 4, 6, 13, 15, 16](https://abookapart.com/collections/books)
  - [Smashing Magazine ](https://www.smashingmagazine.com/category/responsive-design/)
    - [Responsive Web and Desktop Dev with Flutter](https://www.smashingmagazine.com/2020/04/responsive-web-desktop-development-flutter/)
    - [Designing Complex Web Tables](https://www.smashingmagazine.com/2019/09/designing-complex-responsive-tables-wordpress/) (Wordpress, but good general advice)
    - [How to architect a complex web table ](https://www.smashingmagazine.com/2019/02/complex-web-tables/)
    - [Table design patterns on the web](https://www.smashingmagazine.com/2019/01/table-design-patterns-web/)
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

# Dependencies

## Epic

- [ ] bcgov/wps/issues/1402
- [ ] bcgov/wps/issues/1410
- [ ] bcgov/wps/issues/1718
- [ ] bcgov/wps/issues/1827
