### ISSUE TITLE
FBP Go: App Strategy

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1709]
**Describe the task**
Feb 15 meeting booked to discuss UX support, product strategy, launch strategy, prioritization. 

**Acceptance Criteria**
- [x] initial meeting Feb 15
- [x] decision: turn into recurring meeting until April 
- [ ] app in crews hands by April 15 

**Additional context**
- Add any other context about the task here.
- Or here
