### ISSUE TITLE
HFI Calculator: Testing with FCs

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1714]
**Describe the task**
Observe someone(s) in each FC using the HFI Calculator to do prep. Would be looking for where they struggle/experience friction, then invite open feedback. 

- Looking at the process of setting the prep days, modifying fire starts, collaboration between Z/RWCO - Plans - other prep day stakeholders, and exporting a PDF record. 
- Looking for usability issues, functionality dealbreakers, anything that could impede clear and confident decision making or prep morning workflows. 

Have we solved the problems our product set out to address?
- time on task
- reduce human error 
- standardize decision making
- facilitate Plans/R/Z/Forecaster collaboration
- confidence and trust  
- satisfaction / ease of use

**STATUS:** 
Updated May 5 — Sprint Planning
- [X] Kamloops: active
- [X] Prince George: active
- [X] Northwest: active
- [X] Southeast: scheduled 
- [ ] Coastal: waiting for it to stop raining 
- [ ] Cariboo: pending 

**Acceptance Criteria**
- [x] reach out to FCs - invite / recruit / schedule
- [ ] write test script - PO / team feedback 

**Additional context**
- Add any other context about the task here.
- Or here
