### ISSUE TITLE
Roadmap Research: Phase 1 — PSU Foundations

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1819]
**Describe the task**
Gathering a sense of the PSU lay of the land - building a foundation.

**Acceptance Criteria**
- [ ] google-fu - PSU around the world 
- [ ] [document](https://bcgov.sharepoint.com/:w:/t/01324/Eezg9x7bgspDsp1QX8K4zpgB9O81LEwX9P0AAPz7th_XzQ?e=upaDS1) - please feel free to comment or contribute (track changes appreciated) 
- [ ] discuss
- [ ] plan next research phase (knowledge board - assumptions, facts, questions) user needs and business goals 

**Additional context**
- Add any other context about the task here.
- Or here
