### ISSUE TITLE
FireBAT: POs review backlog, collab with UX on research insights & story mapping

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1864]
**Describe the task**
Background: Research was done, a sharing session and MVP workshop was held with the entire team, findings are somewhat captured in the Roadmap: User Story Mapping board (Miro) where the epics or major MVP features are captured with details in comments. 

Task: prepare backlog for next sprint with ballpark estimation to scope MVP for June delivery. 

**Acceptance Criteria**
- [x] [problem brief/transition document](https://bcgov.sharepoint.com/:w:/t/01324/EZVImhLz_jlKmdlYH4BoHjMBbXGC-Y0nWzUqnbzYkJ7Rtg?e=EEJyNT)  
  - [x] review [phase 1: Fire Behaviour Calculator Miro](https://miro.com/app/board/o9J_lWy3dqw=/) The Fire Behaviour Calculator will exist in a connected workflow with the Fire Behaviour Advisory Tool. Initially conceptualized as one product, decided to split out into 2 so that the Calc. can be a sandbox (tinkering) and the FBA automation can be more restricted (OSWS 5) 
  - [x] review [research findings and MVP concept workshop](https://miro.com/app/board/o9J_l6ii2lw=/?moveToWidget=3074457366868913401&cot=14) (Human Experience Miro)
  - [x] review [FireBAT story mapping in the roadmap](https://miro.com/app/board/o9J_kwsQfD8=/?moveToWidget=3458764515687556475&cot=14) (Roadmap Miro)
  - [ ] asess dev progress https://psu.nrs.gov.bc.ca/fire-behaviour-advisory
  - [ ] assess FireBAT (new) Backlog
- [ ] do new [user story mapping using this template](https://miro.com/app/board/o9J_l6ii2lw=/?moveToWidget=3458764514903385811&cot=14), including estimation using t-shirt sizes (Human Experience Miro)
- [ ] flesh out and prioritize FireBAT (new) Backlog for next sprint starting on **April 21**

**Additional context**
- Add any other context about the task here.
- Or here
