### ISSUE TITLE
Wildfire Preparedness User Research

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#189]
**Describe the task**
user research with all relevant positions regarding preparedness decisions and workflow, what data they are interested in and how they currently get that data

**Acceptance Criteria**
- [ ] Identify all relevant positions
- [ ] Document research
- [ ] 

**Additional context**
- Linked to Personas
# Dependencies

## Epic

- [ ] bcgov/wps/issues/171
- [ ] bcgov/wps/issues/184
- [ ] bcgov/wps/issues/185
- [ ] bcgov/wps/issues/186
- [ ] bcgov/wps/issues/187
- [ ] bcgov/wps/issues/188
- [ ] bcgov/wps/issues/256
- [ ] bcgov/wps/issues/311
- [ ] bcgov/wps/issues/329
- [ ] bcgov/wps/issues/330
- [ ] bcgov/wps/issues/331
- [ ] bcgov/wps/issues/339
- [ ] bcgov/wps/issues/340
- [ ] bcgov/wps/issues/349
