### ISSUE TITLE
Backlog tasks homework

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1894]
- [x] #1424 – Conor ; Material UI. Split ticket into two parts, 1st part to go into next sprint.
- [x] #1859 – Dana + Tess ; Planning area ready. I have many questions, not enough context to estimate. Need to pin down exact behavior better. ALSO. Unclear if this is something we push out later or if we’re doing it in before fully switching to New FireBAT.
- [x] #1886 – Dana ; We don’t know if this is something we need for this fire season or not. What’s the priority? If it’s high priority, we need to have more conversations and do some UX research and break into more stories.
- [x] #1537 – Conor ; Add columns to FBA. This story needs to be reviewed with respect to what work has already been completed, and then broken up into smaller parts.
- [x] #1887 – Sybrand ; Dynamic Thiessen polygons & stations. If stations are going to be changing all the time, we need to dynamically update polygons and stations. Write a big story.
- [x] # 1910 – Sybrand ; Write a story for migrating to CrunchyDB
- [x] #1794 – Andrea ; Re. critical hours. We don’t even know how slow it is right now, we need the story to be fleshed out some more. The 1 second per station number is also garbage, we’d want to calculate the critical hours for a whole slew of stations really fast.
- [x] #1888 – Neal + Sybrand; Up to date Thessian polygons. To do this, Neal needs the list of stations to be used, Sybrand will provide list of station from WF1

**Comment by tessmgood** [comment]
@dthicks this is a test: did you get a notification? if yes, please respond in zenhub

**Next steps on 1859 and 1886:**
- Should we be prioritizing this work in the next sprint, or pushing it out?
- #1859: Planning Area ‘Ready’: I’m hopeful we can find a lean way to tackle this — it’s been heavily user requested in Ops CoP and Sprint Reviews. Not implementing means friction and uncertainty / manual offline collaboration between Plans, Rs, Zs.    
  - Another way of semi-solving this is loading fire start fields as empty rather than a default 0-1 or 0-2, so folks could assume empty = default state. Might not be much faster, we previously de-scoped this. Doesn’t address station include/exclude decisions. Still ambiguous.
- On #1886: Station Admin – there are manual workarounds for this, but it will put stress on our dev team and may cause user pain if urgent requests come up outside of core working hours, esp. given what we know about the station network this year, feels risky?
- #1714: I can get us HFI clarity if I pull the trigger on this (knowing that setting up 6 FC sessions might be slow-ish w Easter and spring schedules) – shall I start reaching out to the FCs?

**Comment by conbrad** [comment]
Split #1424 into #1896 and #1898
Split #1537 into #1902 and #1903
