### ISSUE TITLE
FBP Go! UX Stuff

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1990]
**Describe the task**
UX support for getting FBP over the finish line

**Acceptance Criteria**
- [x] develop new color palette 
- [x] collaboration session with SS
- [x] card sort (external) - set up and monitor 
- [x] review testflight feedback from 390 
- [x] provide design options for the slider feedback (hot dog fingers)
- [x] planning meeting 

This was more than a 1!
