### ISSUE TITLE
05-22 Innovation — UX: FireBAT Problem Framing 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#2053]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- tie in some learning: [Figure it Out ](https://rosenfeldmedia.com/books/figure-it-out/)— from information to understanding
- review research to date
- break down [OSWS # 5](https://intranet.gov.bc.ca/bcws/resource-centre/document-type/standards?) into a flow 
  - map reality against flow (artifact for stakeholders) 
- conduct additional session: working with EK to pull in someone from each Fire Centre
  - use problem framing canvas
- analyze with NM
- synthesize, document 
- to be shared with those who have accountability (SWOO) and Exec — gain feedback and buy-in on a way forward

![Problem-Framing Canvas.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/7d351801-edb7-4908-b474-fa87a241874a)

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

# Dependencies

## Epic

- [ ] bcgov/wps/issues/2055
