### ISSUE TITLE
Roadmap: Visuals

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2829]
VISION
Ecosystem of Predictive Services Applications (Research, Innovation & Software Tools)

NOW
MoreCast 2.0 Skill Scoring
Predictive Services Dashboards: Business Intelligence & Real time info
- Spatial Fire Management System Revamp (SFMS: ASA & MoreCast 2.0 Integration)
- Fire Occurrence Prediction 
- Datamart Weather Station Data Visualization; Exposing our Data/APIs

PROBABLE (NEXT)
Initial Attack Performance (Escape Fires)
Resource Demand Planner
AI Grass Curing Application
[ 3 placeholder products ] 1x D Product, 1x C Product, 1x B Product 

POSSIBLE (LATER)
Predictive (Data) Services [ Single Dashboard: Fires & C-Haines ] 

Context: 

- Email about Premier's task force, first bullet (https://news.gov.bc.ca/releases/2023EMCR0064-001534). Line of sight connection to Agile roadmap.
- How the tool will be used, how will BC wildfire service look 3-5 years down the road because of roadmap?
- Example 1 for consideration is info graphics used to explain complex scientific research (https://wildfireanalytics.org/simulated-burn-probability.html).
- Example 2 for consideration is the YouTube animation video used to explain the cultural and prescribed fire program (https://www.youtube.com/watch?v=nMg4l5ClG70&t=1s). Not expecting a video, just an idea.

**Acceptance Criteria**

- [x] Create workshop for team to collaborate on apps to work on, expected month/year for development.
- [x] Priortize application work on matrix to identify potential scope of work.
- [x] Adjust horizontal visual timeline to include priority apps and any nested tasks.
- [x] Present to Forecasters and partners to establish buy-in.

**Comment by rajpersram** [comment]
First step of this is to create a rough timeline, going with the now-next-later paradigm. This can be found on Miro at https://miro.com/app/board/uXjVNbyxGFI=/

**Comment by rajpersram** [comment]
Next step may use a multislide presentation talking about the overall vision, goals, successes, possibly funding and new project rationale, rolled up into a slide deck via Canva.

**Comment by rajpersram** [comment]
Thanks for the updates over the xmas time, @NicolasLivanos. Moving to Done for this Sprint.
