### ISSUE TITLE
Highly Available Database for storing Forecasts and GDPS & RDPS Model Runs

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#294]
**Describe the task**
Create Highly Available Database for storing previous weather forecasts and edited weather forecasts

**Acceptance Criteria**
- [ ] Postgres DB setup in openshift using template
- [ ] Each PR has its own instance of the DB (Cleanup, production DB persists)
- [ ] Postgres DB on local machine 

**Additional context**
- Highly Available Database 
- Geospatial from the start without too much extra effort
- https://github.com/bcgov/silviculture-ipc can we do PostGIS on top of this template

# Dependencies

## Epic

- [ ] bcgov/wps/issues/210
- [ ] bcgov/wps/issues/323
- [ ] bcgov/wps/issues/324
