### ISSUE TITLE
ASA Roadmap: Cadillac

### ISSUE THREAD

**Issue by rajpersram** [bcgov/wps#3616]
As a PSU partner, I want to see a visual representation of a project timeline for developing our Fire Behaviour Advisory online tools towards the "Cadillac" version based on the feedback gathered from the Fire Center Operation Specialists/Officers that's recorded on the Miro Board "[PSU Journey Maps - ASA](https://miro.com/app/board/uXjVN7wCOfc=/?moveToWidget=3458764577486085001&cot=14)" so that I can align resources to enable the team to meet these goals in a timely fashion.

**Background Information:**
During winter of 2024, Operation Specialsts were interviewed to learn more about their workflow around issuing FBAs, covering the steps of judging whether one is needed, the communication and dissemination of the advisory to the ground crew. 

Eric Kopetsky is our main contact which we will align with each sprint to ensure we 'Skate to where the puck is going to be, not where it has been.' to ensure timely ongoing releasing of prioritized goals for standardizing the FBA format and communication among all Fire Centers and crew.

The primary MVP focus will be on the FBA template, while the Cadillac version will represent our best approximation of how the entire workflow can be actualized.

**Acceptance Criteria:**
- [ ] Establish a Fire Behaviour Advisory template, intended to be used by all Fire Centers
- [ ] Create Gantt Chart to outline a rough timeline for implementing features over at least a one year period
- [ ] Identify major systems involved in the FBA workflow from inception to reception.
- [ ] Provide wireframe ideas for major touchpoints that are integral to FBA workflow process.

**Comment by rajpersram** [comment]
First draft of FBA Roadmap ready to [view in Miro here](https://miro.com/app/board/uXjVN7wCOfc=/?moveToWidget=3458764588862217242&cot=14).
