### ISSUE TITLE
MoreCast: Wind

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#479]
this Epic contains the display of Wind Variables in Morecast
# Dependencies

## Epic

- [ ] bcgov/wps/issues/383
- [ ] bcgov/wps/issues/386
- [ ] bcgov/wps/issues/413
- [ ] bcgov/wps/issues/609
- [ ] bcgov/wps/issues/610
- [ ] bcgov/wps/issues/611
- [ ] bcgov/wps/issues/663
- [ ] bcgov/wps/issues/740
- [ ] bcgov/wps/issues/787
