### ISSUE TITLE
MoreCast UI Enhancements

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#538]
These enhancements impact the look and feel of the front end to impact the users experience
# Dependencies

## Epic

- [ ] bcgov/wps/issues/488
- [ ] bcgov/wps/issues/489
- [ ] bcgov/wps/issues/490
- [ ] bcgov/wps/issues/492
- [ ] bcgov/wps/issues/503
- [ ] bcgov/wps/issues/505
- [ ] bcgov/wps/issues/534
- [ ] bcgov/wps/issues/537
- [ ] bcgov/wps/issues/545
- [ ] bcgov/wps/issues/550
- [ ] bcgov/wps/issues/572
- [ ] bcgov/wps/issues/576
- [ ] bcgov/wps/issues/577
- [ ] bcgov/wps/issues/579
- [ ] bcgov/wps/issues/584
- [ ] bcgov/wps/issues/585
- [ ] bcgov/wps/issues/586
- [ ] bcgov/wps/issues/587
- [ ] bcgov/wps/issues/655
- [ ] bcgov/wps/issues/656
- [ ] bcgov/wps/issues/704
- [ ] bcgov/wps/issues/739
- [ ] bcgov/wps/issues/821
- [ ] bcgov/wps/issues/1036
- [ ] bcgov/wps/issues/1037
- [ ] bcgov/wps/issues/1080
- [ ] bcgov/wps/issues/1104
