### ISSUE TITLE
90th Percentile Calculator

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#56]
We need to establish and or confirm the equation that is used to calculate 90% weather values.  
Assumptions:

- Use daily FWI values
- Used pre-determined time range that represents core fire season
- Use selected time range (years of historical data) for the MVP this will be present to 10 years in the past.
# Dependencies

## Epic

- [ ] bcgov/wps/issues/30
- [ ] bcgov/wps/issues/103
- [ ] bcgov/wps/issues/104
- [ ] bcgov/wps/issues/115
- [ ] bcgov/wps/issues/120
- [ ] bcgov/wps/issues/121
- [ ] bcgov/wps/issues/175
- [ ] bcgov/wps/issues/202
- [x] bcgov/wps/issues/203
- [ ] bcgov/wps/issues/204
- [ ] bcgov/wps/issues/207
- [ ] bcgov/wps/issues/255
- [ ] bcgov/wps/issues/269
- [ ] bcgov/wps/issues/271
- [ ] bcgov/wps/issues/305
- [ ] bcgov/wps/issues/308
- [ ] bcgov/wps/issues/337
- [ ] bcgov/wps/issues/338
- [ ] bcgov/wps/issues/389
- [ ] bcgov/wps/issues/390
- [ ] bcgov/wps/issues/391
- [ ] bcgov/wps/issues/392
- [ ] bcgov/wps/issues/393
- [ ] bcgov/wps/issues/394
- [ ] bcgov/wps/issues/395
- [ ] bcgov/wps/issues/583
