### ISSUE TITLE
OCP4 migration

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#604]
**Describe the task**
We need to migration to OCP4.

**Tasks**
Look into Eagle Project and see how they did the migration to OCP4
- [ ] Remove default restrictions
A.C.
default network security policies block everything, open it up to get started
3

Setup security for OCP4
- [ ] Introduce appropriate security policies
- [ ] for every PR there will be a security policy 
A.C.
see Eagle project example. May need an individual security policy for each PR
5

Figure out how to resolve the Docker limit issue
- [ ] Docker limit is no longer an issue
3

- [ ] Create "patroni" base image in tools
3

- [ ] Create "uvicorn-gunicorn-fastapi" base image in tools
2

- [ ] Create matomo, mariadb and matomo-proxy base images in tools
2

- [ ] Create backup-postgres image in tools
2

- [ ] Create backup-mariadb image in tools
2

- [ ] Wire up github job - deployment.prepare-database
      dependent on Patroni Image
8

- [ ] Wire up github job - deployment.prepare-database-backups
       dependent on back up postgres image
5

- [ ] Wire up "Build Image" in deployment.build-and-deploy
         dependent on Gunicorn image
3

- [ ] Wire up "Deploy to Dev" in deployment.build-and-deploy
         dependent on the wire up build image ticket
13

- [ ] Wire up all the cronjobs in deployment.build-and-deploy
           dependent on deploy to dev
3

- [ ] Implement pipeline to production
            dependent on wire up build image ticket
13

- [ ] Configure routes etc for production.
             dependent on Jenkins probably    
3

- [ ] Update zap scan to point to new production endpoint
              Dependent on Jenkins
1

- [ ] Point psu.nrs.gov.bc.ca to new endpoint
              Dependent on Jenkins
2

- [ ] Remove all OCP3 provisioning (Dev builds and production)
1

- [ ] Decommission everything in OCP3
1

**Additional context**
- Ensure cleanup works for every implemented step.
- We'll run in OCP4 and OCP3 in parallel until we've completed migration.
