### ISSUE TITLE
MoreCast: Mapping + Interactions

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#762]
# Dependencies

## Epic

- [ ] bcgov/wps/issues/365
- [ ] bcgov/wps/issues/503
- [ ] bcgov/wps/issues/698
- [ ] bcgov/wps/issues/718
- [ ] bcgov/wps/issues/768
- [ ] bcgov/wps/issues/769
- [ ] bcgov/wps/issues/770
- [ ] bcgov/wps/issues/771
- [ ] bcgov/wps/issues/785
- [ ] bcgov/wps/issues/793
- [ ] bcgov/wps/issues/822
- [ ] bcgov/wps/issues/833
- [ ] bcgov/wps/issues/849
- [x] bcgov/wps/issues/850
- [ ] bcgov/wps/issues/911
- [ ] bcgov/wps/issues/1054
