### ISSUE TITLE
HFI Calculator - Daily Table View with Automation

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#934]
Table View includes:

- Select/Deselect a Wx to in planning area as part of Mean calc
- Daily Table views (MVP)
- Both tables are populated with automation and NO manual inputs
- need to determine true sources for the data used to fill the tables
- Video of table being filled manually: [Link to Video]
(https://bcgov.sharepoint.com/:v:/r/teams/01324/Shared%20Documents/General/UX/HFI-Prep%20Tool/HFI%20Cal%20Process%20Walkthrough%20Videos/peter%20oh%20sad%20ski%20-%20Meeting%20in%20_Preparedness_-20210319_085330-Meeting%20Recording.mp4?csf=1&web=1)

- Link to where the report is generated: http://bcfireweatherp1.nrs.gov.bc.ca/Scripts/Public/Common/Report.asp?Report=Daily

- Daily view columns: 
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/5250c05c-830e-4ee5-a588-f35fc5464b48)
- expand and collapse of Fire Centers
-expand and collapse planning areas

# Dependencies

## Epic

- [ ] bcgov/wps/issues/1006
- [ ] bcgov/wps/issues/1007
- [ ] bcgov/wps/issues/1008
- [ ] bcgov/wps/issues/1009
- [ ] bcgov/wps/issues/1010
- [ ] bcgov/wps/issues/1011
- [ ] bcgov/wps/issues/1012
- [ ] bcgov/wps/issues/1013
- [ ] bcgov/wps/issues/1014
- [ ] bcgov/wps/issues/1017
